[project]
name = "lightsaber"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "wave>=0.0.2",
]

[dependency-groups]
dev = [
    "circuitpython-stubs>=9.2.4",
    "mypy>=1.14.1",
    "ruff>=0.9.4",
]
